service: mpls-garbage-calendar

frameworkVersion: '3'

params:
  default:
    domain: ${sls:stage}.${param:rootDomain}
  prod:
    domain: ${param:rootDomain}

provider:
  name: aws
  runtime: python3.9
  logRetentionInDays: 14

custom:
  customDomain:
    domainName: ${param:domain}
    basePath: mpls-garbage-calendar
    apiType: http
    endpointType: regional

package:
  patterns:
    - '!node_modules/**'
    - '!tests/**'

functions:
  handle_schedule:
    handler: mpls_garbage_calendar/handler.handler
    events:
      - httpApi:
          method: GET
          path: /{schedule_day}


plugins:
  - serverless-python-requirements
  - serverless-domain-manager
